# Generated by Django 3.1.3 on 2020-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200, unique=True)),
                ('calle', models.CharField(max_length=200, unique=True)),
                ('numero', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
