# Generated by Django 3.1.3 on 2020-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nacimiento', models.CharField(max_length=200)),
            ],
        ),
    ]
