# Generated by Django 3.1.3 on 2020-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0002_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueno',
            name='nacimiento',
            field=models.DateTimeField(verbose_name='Fecha de nacimiento'),
        ),
    ]
