# Generated by Django 3.1.3 on 2020-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0004_dueno_locales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dueno',
            name='nick',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='calle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='localidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='provincia',
            field=models.CharField(max_length=200),
        ),
    ]
