# Generated by Django 3.1.3 on 2020-11-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0005_auto_20201128_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='local',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='local',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='local',
            name='provincia',
        ),
        migrations.AddField(
            model_name='local',
            name='direccion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservar.direccion'),
            preserve_default=False,
        ),
    ]
