# Generated by Django 3.1.3 on 2020-11-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0006_auto_20201128_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservar.local')),
                ('especialidades', models.CharField(max_length=200)),
            ],
            bases=('reservar.local',),
        ),
    ]
