# Generated by Django 3.1.3 on 2020-11-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0007_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservar.local')),
                ('hora_clausura', models.TimeField(verbose_name='hora de cierre')),
                ('hora_apertura', models.TimeField(verbose_name='hora de apertura')),
            ],
            bases=('reservar.local',),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservar.local')),
                ('precio_estimado', models.CharField(max_length=200)),
                ('cap_max_total', models.CharField(max_length=200)),
                ('cap_max_mesa', models.CharField(max_length=200)),
            ],
            bases=('reservar.local',),
        ),
    ]
