# Generated by Django 3.1.3 on 2020-11-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0008_pub_restaurante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='password',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservar.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('reservar.usuario',),
        ),
        migrations.AddField(
            model_name='dueno',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservar.usuario'),
            preserve_default=False,
        ),
    ]
