# Generated by Django 3.1.5 on 2021-01-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservaciones.usuario')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.direccion')),
            ],
            bases=('reservaciones.usuario',),
        ),
    ]
