# Generated by Django 3.1.5 on 2021-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0005_auto_20210113_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='duenos',
            field=models.ManyToManyField(through='reservaciones.Dueno', to='reservaciones.Local'),
        ),
    ]
