# Generated by Django 3.1.5 on 2021-01-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0007_auto_20210113_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=500)),
                ('valoracion', models.PositiveSmallIntegerField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.cliente')),
                ('local', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.local')),
            ],
        ),
    ]
