# Generated by Django 3.1.5 on 2021-01-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la reserva')),
                ('hora', models.TimeField(verbose_name='Hora de la reserva')),
                ('descuento', models.PositiveSmallIntegerField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.cliente')),
                ('local', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.local')),
            ],
        ),
    ]
