# Generated by Django 3.1.5 on 2021-01-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0009_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestacion', models.CharField(max_length=500)),
                ('dueno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.dueno')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.review')),
            ],
        ),
    ]
