# Generated by Django 3.1.5 on 2021-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0010_contestacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='duenos',
        ),
        migrations.AlterField(
            model_name='local',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Solo vomité 47 veces'), (1, 'Antes que volver me suicido'), (5, 'Se la chupo al cocinero'), (4, 'Pues está bastante bien la wea'), (3, 'meh')]),
        ),
    ]
