# Generated by Django 3.1.5 on 2021-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0011_auto_20210115_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(4, '4'), (1, '1'), (2, '2'), (3, '3'), (5, '5')]),
        ),
    ]
