# Generated by Django 3.1.5 on 2021-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0014_auto_20210115_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateTimeField(verbose_name='Fecha de nacimiento'),
        ),
    ]
