# Generated by Django 3.1.5 on 2021-01-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.direccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservaciones.local')),
                ('especialidades', models.CharField(max_length=200)),
            ],
            bases=('reservaciones.local',),
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservaciones.local')),
                ('hora_clausura', models.TimeField(verbose_name='hora de cierre')),
                ('hora_apertura', models.TimeField(verbose_name='hora de apertura')),
            ],
            bases=('reservaciones.local',),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservaciones.local')),
                ('precio_estimado', models.CharField(max_length=200)),
                ('cap_max_total', models.CharField(max_length=200)),
                ('cap_max_mesa', models.CharField(max_length=200)),
            ],
            bases=('reservaciones.local',),
        ),
    ]
