# Generated by Django 3.1.5 on 2021-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
