# Generated by Django 3.1.5 on 2021-01-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservaciones.usuario')),
                ('locales', models.ManyToManyField(to='reservaciones.Local')),
            ],
            bases=('reservaciones.usuario',),
        ),
        migrations.AddField(
            model_name='local',
            name='duenos',
            field=models.ManyToManyField(through='reservaciones.Dueno', to='reservaciones.Local'),
        ),
    ]
