# Generated by Django 3.1.5 on 2021-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0006_auto_20210113_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='duenos',
            field=models.ManyToManyField(related_name='_local_duenos_+', through='reservaciones.Dueno', to='reservaciones.Local'),
        ),
    ]
