# Generated by Django 3.1.5 on 2021-01-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0012_auto_20210115_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
