# Generated by Django 3.1.5 on 2021-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0013_auto_20210115_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
